(PUP-10650) Remove PTypeType and PTypeSetType from RichData
puppetlabs/puppet pull request #8299
Opened 2020-08-28 00:09 UTC by joshcooper

The RichData alias included Type and TypeSet which correspond to PTypeType and
PTypeSetType. While pcore can serialize those objects, we don't in practice.

Also if lookup returns a large hiera hash that happens to include a top-level
`pcore_version` key, then pops will perform full type inference on the hash,
thinking it's a TypeSetType#instance?. To avoid that pitfall remove the Type and
TypeSet types from RichData.

The `Type` and `TypeSet` types were missing from the
'rich_data_compatibile_types` shared context. So the TypeCalculator specs were
never testing that they were instances of RichData. Had the types been included,
then this commit would have removed them.

2020-08-28 00:10 UTC, joshcooper commented
This is a follow up to #8029 

@hlindberg Thoughts about removing `PTypeType` and `PTypeSetType` from `RichData` in Puppet 7? There are no tests so it's not clear what might break.

2020-08-28 09:05 UTC, hlindberg commented
Conceptually they should be included in `RichData` as without them it isn't possible to serialize them and if that is ever wanted (i.e. if a self describing serialization is wanted - which I think is very useful) would need to change it back, or invent yet another type for that and change serialization to be based on it.

The real problem is that `PTypeSetType` falls back to the generic `instance?` method which performs a type inference. it is slow to infer the type of a large hash (to for example get something like `Hash[String[1,10], Integer[0,100]]` back. It then checks if something of that type is assignable to the type it is testing for. That is bad and sad because a Hash type is not a kind of TypeSet type - so it went to all that trouble only to come up with `false`.

I think the correct thing to do here is to have an instance? method for PTypeSetType that looks like this:
```
def instance?(o, guard = nil)
  return o.is_a?(PTypeSetType)
end
```

And if PTypeType does not have a similar `instance?` then do the corresponding thing there.

2020-08-28 09:32 UTC, hlindberg requested changes
As per my comment above - I think the types should be kept in `RichData` and that the `instance?` should be fixed as suggested. (Needs to be tested naturally, I did not do that except for some command line puppet apply smoke tests).

2020-08-28 11:00 UTC, puppetcla commented
CLA signed by all contributors.

2020-08-31 20:50 UTC, justinstoller commented
Hey, Henrik. Does the type inference in https://github.com/puppetlabs/puppet/pull/8295/files#diff-f785281ca267e80edf86ce03848c3ecaR352-R362 seem correct to you? It's assuming it receives a Hash rather than a PTypeSetType, which seemed sane to me based on how I _thought_ things worked, but I might be missing something.

2020-08-31 21:48 UTC, hlindberg commented
@justinstoller I think there is a confusion over serialization of a PTypeSetType and an instance of that type at runtime. In the type inference, the way I see it, an instance of a Hash is never a PTypeSetType instance so basically the performance problem is because the inference for the PTypeSetType falls back to the default which is to infer the type of the value it is checking and then checking of the returned type is `TypeSet` - and it never will no matter how many keys that hash includes from what a PTypeSetType instance looks like when it is serialized.

You can verify this by having a hash that is the serialization of a `TypeSet` and see that the unmodified code never takes that as being an instance of `TypeSet`. (I kind of did that by setting up a small experiment and running it in the debugger). So - I believe that my 3 line suggestion above is all that is needed to cure the performance problem. (Also look at PTypeType if it has the same problem - it too should also only look at the instance type and not fall back to the expensive default behavior.

2020-08-31 21:53 UTC, hlindberg commented
I should add that was also fooled at first and thought it would make sense to look at keys in the hash. It was when I stepped through the code that I realized that it will never take a Hash instance to be an instance of TypeSet (or Type) in this case. The external representation of those as Hashes are defined by the RichData "human readable" serialization format that is now in use - and that format is never interpreted directly by the type system. 

Hope that makes it more clear what is going on...

2020-08-31 21:56 UTC, hlindberg commented
Also, while the patch that was made speeds things up it would in the odd case (if the "magic keys" are in the hash) fall back to the default behaviour - and that would never take a hash as being a typeset. So while that "works" it isn't the correct solution.

2020-08-31 21:57 UTC, joshcooper commented
@hlindberg thanks for the comments. [Earlier you suggested](https://tickets.puppetlabs.com/browse/PUP-10628?focusedCommentId=755744&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-755744)

> Speeding up the inference is still of value - there may be some obvious things that can be done to make it faster to discriminate if a hash could possibly represent a type or typeset.

And [in this comment](https://tickets.puppetlabs.com/browse/PUP-10628?focusedCommentId=756045&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-756045):

> I think it is may be as easy as checking if it has the key "pcore_uri" - which should be present and signifies that "this is something that has to do with pcore"

I'm happy to change `PTypeSetType#instance?` to check if `o.is_a?(PTypeSetType)`, but when would the "if a hash could possibly represent a type or typeset" check occur? Would that be in the `PTypeSetType#assignable?` method? Currently it inherits the base implementation.

2020-08-31 22:02 UTC, hlindberg commented
@joshcooper sorry about that, I was fooled by the idea that it would possibly accept a hash instance as a typeset instance. But I was wrong.

I think the `instance?` method should be implemented as I suggested. And there is never the need to fall back to the default (inherited behaviour) since at runtime an instance of `TypeSet` is never an instance of `Hash`.

2020-09-01 16:27 UTC, joshcooper commented
Switching to `is_a?` will be done in https://github.com/puppetlabs/puppet/pull/8307. I'm going to close this as won't do.

2020-09-01 16:27 UTC, closed without merging