(PUP-11187) Add `scripts` file serving mount
puppetlabs/puppet pull request #8711
Opened 2021-07-23 16:28 UTC by lucywyman

This adds a file serving mount "scripts" that loads scripts from the
`scripts/` directory of the specified module. This is for use by
Puppetserve to serve file content and metadata for scripts through a
`scripts` mount_point.

I think this needs some tests but wanted to get up for a demo first.

2021-07-23 17:15 UTC, beechtom requested changes
We should include tests under `spec/unit/file_serving/configuration_spec.rb` and `spec/unit/file_serving/mount/scripts_spec.rb`.

2021-07-23 21:11 UTC, lucywyman commented
Relates to https://github.com/puppetlabs/puppetserver/pull/2560

2021-07-26 20:33 UTC, beechtom approved these changes

2021-07-28 01:41 UTC, joshcooper commented on spec/unit/file_serving/configuration/parser_spec.rb
> +    it "should create an instance of the Modules Mount class" do
copy/pasta `Scripts Mount`?

2021-07-28 01:42 UTC, joshcooper commented on spec/unit/file_serving/mount/scripts_spec.rb
> +    @mount = Puppet::FileServing::Mount::Scripts.new("modules")
```suggestion
    @mount = Puppet::FileServing::Mount::Scripts.new("scripts")
```

2021-07-28 01:48 UTC, joshcooper commented
For posterity, this PR builds on changes added in 600491d04883fdab673b58d51c9a3060b2cc7241, which was a backport to 6.x

Also nearly all of the code in `lib/puppet/file_serving/configuration/*.rb` relates to legacy authorization, when using the `puppet master` application or webrick/passenger. The code was deprecated for a long time and removed in puppet 7. Instead all REST authorization is handled by puppetserver's trapperkeeper auth.conf.

2021-07-28 17:37 UTC, joshcooper approved these changes

2021-07-28 17:37 UTC, merged