(PUP-11190) Fix user resource not removing password on AIX agents
puppetlabs/puppet pull request #8737
Opened 2021-08-11 11:33 UTC by BobosilaVictor

This pull requests adds the `-p` flag to the `rmuser` command, to ensure that the user's password was deleted.

2021-08-11 13:25 UTC, ciprianbadescu commented
@BobosilaVictor , I think it should be open against 6.x branch

2021-08-11 13:28 UTC, ciprianbadescu requested changes

2021-08-11 13:28 UTC, ciprianbadescu commented on lib/puppet/provider/aix_object.rb
> +    [self.class.command(:delete), '-p'] + ia_module_args + [@resource[:name]]
this code is common for `aix` `group` provider and `user` providers and it will add the `-p` argument also to the group delete command

2021-08-12 11:43 UTC, ciprianbadescu commented on lib/puppet/provider/aix_object.rb
> +    if self.class == Puppet::Type::User::ProviderAix
`High-level modules should not depend on low-level modules`

https://en.wikipedia.org/wiki/Dependency_inversion_principle

2021-08-16 07:18 UTC, ciprianbadescu approved these changes

2021-08-16 10:42 UTC, gimmyxd approved these changes
Good to merge after rebase

2021-08-16 12:24 UTC, merged